name = "Fabulously Optimized"
author = "robotkoer"
version = "4.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "522d31231f553b40fa54c8ed79bb3c4678b2969e937b4dc43ac609de631c7836"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
